import type { Dictionary } from "./uz";

export const en: Dictionary = {
  meta: {
    title: "IZO PLUS — PENAPLAST FACTORY | Quality EPS foam",
    description:
      "IZO PLUS — PENAPLAST FACTORY: white, black and crushed EPS penaplast. Density 7–20 kg/m³, thickness 1–60 cm. Prices, 3D view and ordering.",
  },
  nav: {
    products: "Products",
    threeD: "3D Experience",
    production: "Production",
    why: "Why penaplast",
    applications: "Applications",
    about: "About us",
    contact: "Contact",
    order: "PLACE AN ORDER",
    search: "Search",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    theme: "Theme",
    language: "Language",
    call: "Call",
    orderShort: "Order",
  },
  hero: {
    eyebrow: "PENAPLAST",
    h1Line1: "QUALITY PENAPLAST.",
    h1Line2: "RELIABLE CONSTRUCTION.",
    description:
      "PENAPLAST FACTORY produces quality EPS penaplast products for construction, thermal insulation and industry.",
    ctaPrimary: "VIEW PRODUCTS",
    ctaSecondary: "PLACE AN ORDER",
    statProducts: "3 products",
    statDensity: "7–20 kg/m³",
    statThickness: "1–60 cm",
    scroll: "Scroll down",
  },
  products: {
    title: "PRODUCTS",
    subtitle: "White, black and crushed penaplast — choose density and thickness.",
    searchPlaceholder: "Search: name, density, thickness…",
    filterAll: "ALL",
    filterDensity: "Density",
    filterThickness: "Thickness",
    filterDensityLabel: "Density filter",
    filterThicknessLabel: "Thickness filter",
    filterAny: "Any",
    reset: "Reset",
    densityLabel: "DENSITY / PLOTNOST",
    thicknessLabel: "THICKNESS",
    priceLabel: "PRICE",
    detail: "DETAILS",
    order: "PLACE AN ORDER",
    view3d: "View in 3D",
    applicationsLabel: "Applications",
    specLabel: "Specifications",
    resultsCount: (n: number) => `${n} results`,
    showMore: "Show more",
    emptyTitle: "NO PRODUCTS FOUND.",
    emptyReset: "Clear filters",
    crushedNote: "Crushed penaplast has no density/thickness",
    perKg: "/ KG",
    names: {
      oq: "WHITE PENAPLAST",
      qora: "BLACK PENAPLAST",
      maydalangan: "CRUSHED PENAPLAST",
    },
    shortApps: {
      oq: "Home construction, buildings, insulation and packaging",
      qora: "Wall, roof and floor insulation",
      maydalangan: "Crushed material for packaging and filling",
    },
    detailText: {
      oq: "White penaplast — a widely used EPS material for construction and insulation.",
      qora: "Black penaplast — a dark graphite-containing EPS material.",
      maydalangan: "Crushed penaplast — EPS material shredded into small pieces.",
    },
  },
  threeD: {
    title: "3D EXPERIENCE",
    subtitle: "Inspect the penaplast block in 3D: switch product type and thickness.",
    productLabel: "PRODUCT",
    thicknessLabel: "THICKNESS",
    densityLabel: "DENSITY",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    autoRotate: "Auto-rotate",
    autoRotateOn: "Auto-rotate: on",
    autoRotateOff: "Auto-rotate: off",
    activate: "Tap to interact",
    activateHint: "Scroll the page with one finger, or activate to control the 3D view",
    exit: "Exit",
    loading: "Loading 3D…",
    fallbackNote: "3D unavailable — showing a high-quality image.",
    illustration: "Volume shown for illustration",
    order: "PLACE AN ORDER",
    beads: {
      title: "PENAPLAST BEADS",
      subtitle: "The penaplast surface is made of thousands of fused EPS beads.",
      zoom: "Zoom in",
    },
  },
  production: {
    title: "PRODUCTION",
    subtitle: "From raw material to finished product — the production process.",
    steps: [
      {
        num: "01",
        title: "RAW MATERIAL",
        text: "Polystyrene granules (EPS raw material) are received and prepared for production.",
      },
      {
        num: "02",
        title: "PRE-EXPANSION",
        text: "Granules are pre-expanded with steam to the required density.",
      },
      {
        num: "03",
        title: "MOLDING",
        text: "Expanded beads are fused in a mold to form a penaplast block.",
      },
      {
        num: "04",
        title: "CUTTING",
        text: "The block is cut into sheets of the required thickness.",
      },
      {
        num: "05",
        title: "QUALITY CONTROL",
        text: "Density and dimensions are checked.",
      },
      {
        num: "06",
        title: "FINISHED PRODUCT",
        text: "The finished product is prepared for dispatch according to the order.",
      },
    ],
  },
  why: {
    title: "WHY PENAPLAST?",
    subtitle: "Penaplast is a reliable choice for construction and insulation.",
    cards: [
      { icon: "shield", title: "QUALITY PRODUCT", text: "Control at every stage of production." },
      { icon: "gauge", title: "ACCURATE DENSITY", text: "Precise density options from 7 to 20 kg/m³." },
      { icon: "layers", title: "VARIOUS THICKNESS", text: "Thickness choice from 1 cm to 60 cm." },
      {
        icon: "thermometer",
        title: "THERMAL INSULATION",
        text: "Penaplast helps reduce heat loss in a building.",
      },
      {
        icon: "factory",
        title: "MODERN PRODUCTION",
        text: "A precise process from expansion to cutting.",
      },
      {
        icon: "truck",
        title: "FAST DELIVERY",
        text: "Delivery terms are agreed with the manager at the time of the order.",
      },
    ],
  },
  applications: {
    title: "WHERE IS IT USED?",
    subtitle: "Penaplast is used across construction and industry.",
    items: {
      uy: "HOME CONSTRUCTION",
      binolar: "BUILDINGS",
      devor: "WALL INSULATION",
      tom: "ROOF INSULATION",
      pol: "FLOOR INSULATION",
      sovutish: "COOLING SYSTEMS",
      qadoqlash: "PACKAGING",
    },
  },
  about: {
    title: "ABOUT US",
    subtitle: "IZO PLUS — PENAPLAST FACTORY",
    paragraphs: [
      "IZO PLUS — PENAPLAST FACTORY is a plant that produces penaplast (EPS) for construction, thermal insulation and industry.",
      "The plant produces white penaplast, black penaplast and crushed penaplast.",
      "Density options are 7–20 kg/m³, and thickness is chosen in the 1–60 cm range.",
      "You can place an order on the site, via Telegram @penaplast_uz or by phone +998 99 513 22 22.",
    ],
    chipProducts: "3 products",
    chipDensity: "7–20 kg/m³",
    chipThickness: "1–60 cm",
  },
  contact: {
    title: "CONTACT",
    subtitle: "Get in touch for orders and questions.",
    phoneLabel: "PHONE",
    telegramLabel: "TELEGRAM",
    phoneHint: "Tap to call",
    telegramHint: "Opens in a new tab",
    orderCta: "PLACE AN ORDER",
    orderCtaHint: "Fill in the form — a manager will contact you shortly.",
  },
  footer: {
    rights: (year: number) => `© ${year} IZO PLUS`,
    tagline: "PENAPLAST FACTORY",
    navLabel: "Pages",
    contactLabel: "Contact",
  },
  order: {
    title: "ORDER",
    name: "NAME",
    namePlaceholder: "Your name",
    phone: "PHONE NUMBER",
    phonePlaceholder: "+998 99 513 22 22",
    product: "PRODUCT",
    density: "DENSITY / PLOTNOST",
    thickness: "THICKNESS",
    quantity: "QUANTITY",
    note: "NOTE",
    notePlaceholder: "Additional note (optional)",
    submit: "SEND ORDER",
    sending: "SENDING…",
    retry: "Try again",
    telegramFallback: "Write on Telegram",
    close: "Close",
    summaryTitle: "ORDER SUMMARY",
    summary: {
      product: "Product",
      density: "Density",
      thickness: "Thickness",
      quantity: "Quantity",
      price: "Price",
      total: "Estimated total",
    },
    totalNote: "The final price is confirmed by the manager.",
    successTitle: "Your order has been received. We will contact you shortly.",
    errorTitle:
      "The order was not sent. Please try again or call +998 99 513 22 22.",
    units: { dona: "pcs", kg: "kg" },
    dash: "—",
  },
  search: {
    placeholder: "Search by product, density or thickness…",
    count: (n: number) => `${n} results`,
    empty: "Nothing found",
    hint: "Enter — search, Esc — clear",
    open: "Search",
  },
  validation: {
    nameRequired: "Enter your name",
    nameMin: "Name must be at least 2 characters",
    nameMax: "Name must not exceed 80 characters",
    phoneRequired: "Enter your phone number",
    phoneInvalid: "Invalid phone number. Example: +998 99 513 22 22",
    quantityInvalid: "Quantity must be at least 1",
    quantityMax: "Quantity is too large",
    noteMax: "Note must not exceed 500 characters",
  },
};
